
replicas: 1

nameOverride: ""
fullnameOverride: ""

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0
  
nodeSelector:
  routing-osrm/role: routing-osrm

osrm:
  backend: 
    image: telenavmap/osrm-backend-within-mapdata:no.86-20200114-master-telenav-e85d5ca-compile27-20200119T171300CST-michigan-latest
    command: ["/bin/sh", "-c", "export LOG_FILE=/osrm-logs/$(date -u +%Y%m%dT%H%M%S)-${HOSTNAME}.log; /docker-entrypoint.sh routed_no_traffic_startup 2>&1 | while read LINE; do echo \"[$(date \"+%Y-%m-%dT%H:%M:%S %Z\")] ${LINE}\">>${LOG_FILE}; done;" ]
    mountPath: "/osrm-logs"
    
logsVolume: 
  name: osrm-logs-volume
  nfs:
    server: fs-3941ca92.efs.us-west-2.amazonaws.com
    path: /

