name: Release Docker - osrm-backend 

on: 
  push:
    tags:
    - 'v*' # semver, e.g., v10.1.0

env:
  IMAGE_NAME: osrm-backend
  DOCKERFILE_PATH: docker-orchestration/osrm-backend/
  DOCKERHUB_REGISTRY: telenavmap

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set IMAGE_TAG env # env IMAGE_TAG=tag-name
      run: echo IMAGE_TAG=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
      
    - name: Comma-separated image tags 
      run: echo COMMA_SEPARATED_IMAGE_TAGS=${IMAGE_TAG} >> ${GITHUB_ENV}
    - name: Append latest tag for release # env '${IMAGE_TAG},latest'
      run: echo COMMA_SEPARATED_IMAGE_TAGS=${COMMA_SEPARATED_IMAGE_TAGS},latest >> ${GITHUB_ENV}
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0

    - name: Build & Publish to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.IMAGE_NAME }}
        username: ${{ secrets.TELENAVMAP_DOCKERHUB_USERNAME }}
        password: ${{ secrets.TELENAVMAP_DOCKERHUB_TOKEN }}
        snapshot: false
        workdir: ${{ env.DOCKERFILE_PATH }}
        tags: "${{ env.COMMA_SEPARATED_IMAGE_TAGS }}"
        buildargs: "GIT_COMMIT=${{ github.sha }},IMAGE_TAG=${{ env.IMAGE_TAG }}"

